
// To check if a library is compiled with CocoaPods you
// can use the `COCOAPODS` macro definition which is
// defined in the xcconfigs so it is available in
// headers also when they are imported in the client
// project.


// AFNetworking
#define COCOAPODS_POD_AVAILABLE_AFNetworking
#define COCOAPODS_VERSION_MAJOR_AFNetworking 2
#define COCOAPODS_VERSION_MINOR_AFNetworking 5
#define COCOAPODS_VERSION_PATCH_AFNetworking 0

// AFNetworking/NSURLConnection
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLConnection
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLConnection 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLConnection 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLConnection 0

// AFNetworking/NSURLSession
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLSession
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLSession 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLSession 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLSession 0

// AFNetworking/Reachability
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Reachability
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Reachability 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Reachability 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Reachability 0

// AFNetworking/Security
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Security
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Security 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Security 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Security 0

// AFNetworking/Serialization
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Serialization
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Serialization 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Serialization 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Serialization 0

// AFNetworking/UIKit
#define COCOAPODS_POD_AVAILABLE_AFNetworking_UIKit
#define COCOAPODS_VERSION_MAJOR_AFNetworking_UIKit 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_UIKit 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_UIKit 0

// CSNotificationView
#define COCOAPODS_POD_AVAILABLE_CSNotificationView
#define COCOAPODS_VERSION_MAJOR_CSNotificationView 0
#define COCOAPODS_VERSION_MINOR_CSNotificationView 5
#define COCOAPODS_VERSION_PATCH_CSNotificationView 3

// CSNotificationView-AFNetworking
#define COCOAPODS_POD_AVAILABLE_CSNotificationView_AFNetworking
#define COCOAPODS_VERSION_MAJOR_CSNotificationView_AFNetworking 0
#define COCOAPODS_VERSION_MINOR_CSNotificationView_AFNetworking 1
#define COCOAPODS_VERSION_PATCH_CSNotificationView_AFNetworking 0

// CocoaLumberjack
#define COCOAPODS_POD_AVAILABLE_CocoaLumberjack
#define COCOAPODS_VERSION_MAJOR_CocoaLumberjack 1
#define COCOAPODS_VERSION_MINOR_CocoaLumberjack 9
#define COCOAPODS_VERSION_PATCH_CocoaLumberjack 2

// CocoaLumberjack/Core
#define COCOAPODS_POD_AVAILABLE_CocoaLumberjack_Core
#define COCOAPODS_VERSION_MAJOR_CocoaLumberjack_Core 1
#define COCOAPODS_VERSION_MINOR_CocoaLumberjack_Core 9
#define COCOAPODS_VERSION_PATCH_CocoaLumberjack_Core 2

// CocoaLumberjack/Extensions
#define COCOAPODS_POD_AVAILABLE_CocoaLumberjack_Extensions
#define COCOAPODS_VERSION_MAJOR_CocoaLumberjack_Extensions 1
#define COCOAPODS_VERSION_MINOR_CocoaLumberjack_Extensions 9
#define COCOAPODS_VERSION_PATCH_CocoaLumberjack_Extensions 2

// CrashlyticsFramework
#define COCOAPODS_POD_AVAILABLE_CrashlyticsFramework
// This library does not follow semantic-versioning,
// so we were not able to define version macros.
// Please contact the author.
// Version: 2.2.5.2.

// CrashlyticsLumberjack
#define COCOAPODS_POD_AVAILABLE_CrashlyticsLumberjack
#define COCOAPODS_VERSION_MAJOR_CrashlyticsLumberjack 1
#define COCOAPODS_VERSION_MINOR_CrashlyticsLumberjack 0
#define COCOAPODS_VERSION_PATCH_CrashlyticsLumberjack 2

// DZNEmptyDataSet
#define COCOAPODS_POD_AVAILABLE_DZNEmptyDataSet
#define COCOAPODS_VERSION_MAJOR_DZNEmptyDataSet 1
#define COCOAPODS_VERSION_MINOR_DZNEmptyDataSet 4
#define COCOAPODS_VERSION_PATCH_DZNEmptyDataSet 1

// ECSlidingViewController
#define COCOAPODS_POD_AVAILABLE_ECSlidingViewController
#define COCOAPODS_VERSION_MAJOR_ECSlidingViewController 2
#define COCOAPODS_VERSION_MINOR_ECSlidingViewController 0
#define COCOAPODS_VERSION_PATCH_ECSlidingViewController 3

// EGOCache
#define COCOAPODS_POD_AVAILABLE_EGOCache
#define COCOAPODS_VERSION_MAJOR_EGOCache 2
#define COCOAPODS_VERSION_MINOR_EGOCache 1
#define COCOAPODS_VERSION_PATCH_EGOCache 0

// FSImageViewer
#define COCOAPODS_POD_AVAILABLE_FSImageViewer
#define COCOAPODS_VERSION_MAJOR_FSImageViewer 2
#define COCOAPODS_VERSION_MINOR_FSImageViewer 6
#define COCOAPODS_VERSION_PATCH_FSImageViewer 4

// FlurrySDK
#define COCOAPODS_POD_AVAILABLE_FlurrySDK
#define COCOAPODS_VERSION_MAJOR_FlurrySDK 5
#define COCOAPODS_VERSION_MINOR_FlurrySDK 4
#define COCOAPODS_VERSION_PATCH_FlurrySDK 0

// FlurrySDK/FlurrySDK
#define COCOAPODS_POD_AVAILABLE_FlurrySDK_FlurrySDK
#define COCOAPODS_VERSION_MAJOR_FlurrySDK_FlurrySDK 5
#define COCOAPODS_VERSION_MINOR_FlurrySDK_FlurrySDK 4
#define COCOAPODS_VERSION_PATCH_FlurrySDK_FlurrySDK 0

// InAppSettingsKit
#define COCOAPODS_POD_AVAILABLE_InAppSettingsKit
#define COCOAPODS_VERSION_MAJOR_InAppSettingsKit 2
#define COCOAPODS_VERSION_MINOR_InAppSettingsKit 3
#define COCOAPODS_VERSION_PATCH_InAppSettingsKit 0

// MarqueeLabel
#define COCOAPODS_POD_AVAILABLE_MarqueeLabel
#define COCOAPODS_VERSION_MAJOR_MarqueeLabel 2
#define COCOAPODS_VERSION_MINOR_MarqueeLabel 0
#define COCOAPODS_VERSION_PATCH_MarqueeLabel 8

// Sidecar
#define COCOAPODS_POD_AVAILABLE_Sidecar
#define COCOAPODS_VERSION_MAJOR_Sidecar 0
#define COCOAPODS_VERSION_MINOR_Sidecar 2
#define COCOAPODS_VERSION_PATCH_Sidecar 0

// Sidecar/Non-ARC
#define COCOAPODS_POD_AVAILABLE_Sidecar_Non_ARC
#define COCOAPODS_VERSION_MAJOR_Sidecar_Non_ARC 0
#define COCOAPODS_VERSION_MINOR_Sidecar_Non_ARC 2
#define COCOAPODS_VERSION_PATCH_Sidecar_Non_ARC 0

