
// To check if a library is compiled with CocoaPods you
// can use the `COCOAPODS` macro definition which is
// defined in the xcconfigs so it is available in
// headers also when they are imported in the client
// project.


// AFNetworking
#define COCOAPODS_POD_AVAILABLE_AFNetworking
#define COCOAPODS_VERSION_MAJOR_AFNetworking 1
#define COCOAPODS_VERSION_MINOR_AFNetworking 3
#define COCOAPODS_VERSION_PATCH_AFNetworking 4

// Asterism
#define COCOAPODS_POD_AVAILABLE_Asterism
#define COCOAPODS_VERSION_MAJOR_Asterism 1
#define COCOAPODS_VERSION_MINOR_Asterism 0
#define COCOAPODS_VERSION_PATCH_Asterism 0

// CocoaLumberjack
#define COCOAPODS_POD_AVAILABLE_CocoaLumberjack
#define COCOAPODS_VERSION_MAJOR_CocoaLumberjack 2
#define COCOAPODS_VERSION_MINOR_CocoaLumberjack 0
#define COCOAPODS_VERSION_PATCH_CocoaLumberjack 0

// CocoaLumberjack/CLI
#define COCOAPODS_POD_AVAILABLE_CocoaLumberjack_CLI
#define COCOAPODS_VERSION_MAJOR_CocoaLumberjack_CLI 2
#define COCOAPODS_VERSION_MINOR_CocoaLumberjack_CLI 0
#define COCOAPODS_VERSION_PATCH_CocoaLumberjack_CLI 0

// CocoaLumberjack/Core
#define COCOAPODS_POD_AVAILABLE_CocoaLumberjack_Core
#define COCOAPODS_VERSION_MAJOR_CocoaLumberjack_Core 2
#define COCOAPODS_VERSION_MINOR_CocoaLumberjack_Core 0
#define COCOAPODS_VERSION_PATCH_CocoaLumberjack_Core 0

// CocoaLumberjack/Extensions
#define COCOAPODS_POD_AVAILABLE_CocoaLumberjack_Extensions
#define COCOAPODS_VERSION_MAJOR_CocoaLumberjack_Extensions 2
#define COCOAPODS_VERSION_MINOR_CocoaLumberjack_Extensions 0
#define COCOAPODS_VERSION_PATCH_CocoaLumberjack_Extensions 0

// CrashlyticsFramework
#define COCOAPODS_POD_AVAILABLE_CrashlyticsFramework
#define COCOAPODS_VERSION_MAJOR_CrashlyticsFramework 2
#define COCOAPODS_VERSION_MINOR_CrashlyticsFramework 2
#define COCOAPODS_VERSION_PATCH_CrashlyticsFramework 4

// CrashlyticsLumberjack
#define COCOAPODS_POD_AVAILABLE_CrashlyticsLumberjack
#define COCOAPODS_VERSION_MAJOR_CrashlyticsLumberjack 1
#define COCOAPODS_VERSION_MINOR_CrashlyticsLumberjack 0
#define COCOAPODS_VERSION_PATCH_CrashlyticsLumberjack 1

// ECSlidingViewController
#define COCOAPODS_POD_AVAILABLE_ECSlidingViewController
#define COCOAPODS_VERSION_MAJOR_ECSlidingViewController 0
#define COCOAPODS_VERSION_MINOR_ECSlidingViewController 10
#define COCOAPODS_VERSION_PATCH_ECSlidingViewController 0

// EGOTableViewPullRefresh
#define COCOAPODS_POD_AVAILABLE_EGOTableViewPullRefresh
#define COCOAPODS_VERSION_MAJOR_EGOTableViewPullRefresh 0
#define COCOAPODS_VERSION_MINOR_EGOTableViewPullRefresh 2
#define COCOAPODS_VERSION_PATCH_EGOTableViewPullRefresh 0

// FlurrySDK
#define COCOAPODS_POD_AVAILABLE_FlurrySDK
#define COCOAPODS_VERSION_MAJOR_FlurrySDK 5
#define COCOAPODS_VERSION_MINOR_FlurrySDK 4
#define COCOAPODS_VERSION_PATCH_FlurrySDK 0

// FlurrySDK/FlurrySDK
#define COCOAPODS_POD_AVAILABLE_FlurrySDK_FlurrySDK
#define COCOAPODS_VERSION_MAJOR_FlurrySDK_FlurrySDK 5
#define COCOAPODS_VERSION_MINOR_FlurrySDK_FlurrySDK 4
#define COCOAPODS_VERSION_PATCH_FlurrySDK_FlurrySDK 0

// FormatterKit
#define COCOAPODS_POD_AVAILABLE_FormatterKit
#define COCOAPODS_VERSION_MAJOR_FormatterKit 1
#define COCOAPODS_VERSION_MINOR_FormatterKit 7
#define COCOAPODS_VERSION_PATCH_FormatterKit 0

// FormatterKit/AddressFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_AddressFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_AddressFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_AddressFormatter 7
#define COCOAPODS_VERSION_PATCH_FormatterKit_AddressFormatter 0

// FormatterKit/ArrayFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_ArrayFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_ArrayFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_ArrayFormatter 7
#define COCOAPODS_VERSION_PATCH_FormatterKit_ArrayFormatter 0

// FormatterKit/ColorFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_ColorFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_ColorFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_ColorFormatter 7
#define COCOAPODS_VERSION_PATCH_FormatterKit_ColorFormatter 0

// FormatterKit/LocationFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_LocationFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_LocationFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_LocationFormatter 7
#define COCOAPODS_VERSION_PATCH_FormatterKit_LocationFormatter 0

// FormatterKit/NameFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_NameFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_NameFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_NameFormatter 7
#define COCOAPODS_VERSION_PATCH_FormatterKit_NameFormatter 0

// FormatterKit/OrdinalNumberFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_OrdinalNumberFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_OrdinalNumberFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_OrdinalNumberFormatter 7
#define COCOAPODS_VERSION_PATCH_FormatterKit_OrdinalNumberFormatter 0

// FormatterKit/TimeIntervalFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_TimeIntervalFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_TimeIntervalFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_TimeIntervalFormatter 7
#define COCOAPODS_VERSION_PATCH_FormatterKit_TimeIntervalFormatter 0

// FormatterKit/URLRequestFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_URLRequestFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_URLRequestFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_URLRequestFormatter 7
#define COCOAPODS_VERSION_PATCH_FormatterKit_URLRequestFormatter 0

// FormatterKit/UnitOfInformationFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_UnitOfInformationFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_UnitOfInformationFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_UnitOfInformationFormatter 7
#define COCOAPODS_VERSION_PATCH_FormatterKit_UnitOfInformationFormatter 0

// InAppSettingsKit
#define COCOAPODS_POD_AVAILABLE_InAppSettingsKit
#define COCOAPODS_VERSION_MAJOR_InAppSettingsKit 2
#define COCOAPODS_VERSION_MINOR_InAppSettingsKit 1
#define COCOAPODS_VERSION_PATCH_InAppSettingsKit 0

// MarqueeLabel
#define COCOAPODS_POD_AVAILABLE_MarqueeLabel
#define COCOAPODS_VERSION_MAJOR_MarqueeLabel 1
#define COCOAPODS_VERSION_MINOR_MarqueeLabel 5
#define COCOAPODS_VERSION_PATCH_MarqueeLabel 0

// TestFlightSDK
#define COCOAPODS_POD_AVAILABLE_TestFlightSDK
#define COCOAPODS_VERSION_MAJOR_TestFlightSDK 3
#define COCOAPODS_VERSION_MINOR_TestFlightSDK 0
#define COCOAPODS_VERSION_PATCH_TestFlightSDK 2

// libextobjc
#define COCOAPODS_POD_AVAILABLE_libextobjc
#define COCOAPODS_VERSION_MAJOR_libextobjc 0
#define COCOAPODS_VERSION_MINOR_libextobjc 4
#define COCOAPODS_VERSION_PATCH_libextobjc 0

// libextobjc/EXTADT
#define COCOAPODS_POD_AVAILABLE_libextobjc_EXTADT
#define COCOAPODS_VERSION_MAJOR_libextobjc_EXTADT 0
#define COCOAPODS_VERSION_MINOR_libextobjc_EXTADT 4
#define COCOAPODS_VERSION_PATCH_libextobjc_EXTADT 0

// libextobjc/EXTConcreteProtocol
#define COCOAPODS_POD_AVAILABLE_libextobjc_EXTConcreteProtocol
#define COCOAPODS_VERSION_MAJOR_libextobjc_EXTConcreteProtocol 0
#define COCOAPODS_VERSION_MINOR_libextobjc_EXTConcreteProtocol 4
#define COCOAPODS_VERSION_PATCH_libextobjc_EXTConcreteProtocol 0

// libextobjc/EXTKeyPathCoding
#define COCOAPODS_POD_AVAILABLE_libextobjc_EXTKeyPathCoding
#define COCOAPODS_VERSION_MAJOR_libextobjc_EXTKeyPathCoding 0
#define COCOAPODS_VERSION_MINOR_libextobjc_EXTKeyPathCoding 4
#define COCOAPODS_VERSION_PATCH_libextobjc_EXTKeyPathCoding 0

// libextobjc/EXTNil
#define COCOAPODS_POD_AVAILABLE_libextobjc_EXTNil
#define COCOAPODS_VERSION_MAJOR_libextobjc_EXTNil 0
#define COCOAPODS_VERSION_MINOR_libextobjc_EXTNil 4
#define COCOAPODS_VERSION_PATCH_libextobjc_EXTNil 0

// libextobjc/EXTSafeCategory
#define COCOAPODS_POD_AVAILABLE_libextobjc_EXTSafeCategory
#define COCOAPODS_VERSION_MAJOR_libextobjc_EXTSafeCategory 0
#define COCOAPODS_VERSION_MINOR_libextobjc_EXTSafeCategory 4
#define COCOAPODS_VERSION_PATCH_libextobjc_EXTSafeCategory 0

// libextobjc/EXTScope
#define COCOAPODS_POD_AVAILABLE_libextobjc_EXTScope
#define COCOAPODS_VERSION_MAJOR_libextobjc_EXTScope 0
#define COCOAPODS_VERSION_MINOR_libextobjc_EXTScope 4
#define COCOAPODS_VERSION_PATCH_libextobjc_EXTScope 0

// libextobjc/EXTSelectorChecking
#define COCOAPODS_POD_AVAILABLE_libextobjc_EXTSelectorChecking
#define COCOAPODS_VERSION_MAJOR_libextobjc_EXTSelectorChecking 0
#define COCOAPODS_VERSION_MINOR_libextobjc_EXTSelectorChecking 4
#define COCOAPODS_VERSION_PATCH_libextobjc_EXTSelectorChecking 0

// libextobjc/EXTSynthesize
#define COCOAPODS_POD_AVAILABLE_libextobjc_EXTSynthesize
#define COCOAPODS_VERSION_MAJOR_libextobjc_EXTSynthesize 0
#define COCOAPODS_VERSION_MINOR_libextobjc_EXTSynthesize 4
#define COCOAPODS_VERSION_PATCH_libextobjc_EXTSynthesize 0

// libextobjc/NSInvocation+EXT
#define COCOAPODS_POD_AVAILABLE_libextobjc_NSInvocation_EXT
#define COCOAPODS_VERSION_MAJOR_libextobjc_NSInvocation_EXT 0
#define COCOAPODS_VERSION_MINOR_libextobjc_NSInvocation_EXT 4
#define COCOAPODS_VERSION_PATCH_libextobjc_NSInvocation_EXT 0

// libextobjc/NSMethodSignature+EXT
#define COCOAPODS_POD_AVAILABLE_libextobjc_NSMethodSignature_EXT
#define COCOAPODS_VERSION_MAJOR_libextobjc_NSMethodSignature_EXT 0
#define COCOAPODS_VERSION_MINOR_libextobjc_NSMethodSignature_EXT 4
#define COCOAPODS_VERSION_PATCH_libextobjc_NSMethodSignature_EXT 0

// libextobjc/RuntimeExtensions
#define COCOAPODS_POD_AVAILABLE_libextobjc_RuntimeExtensions
#define COCOAPODS_VERSION_MAJOR_libextobjc_RuntimeExtensions 0
#define COCOAPODS_VERSION_MINOR_libextobjc_RuntimeExtensions 4
#define COCOAPODS_VERSION_PATCH_libextobjc_RuntimeExtensions 0

// libextobjc/UmbrellaHeader
#define COCOAPODS_POD_AVAILABLE_libextobjc_UmbrellaHeader
#define COCOAPODS_VERSION_MAJOR_libextobjc_UmbrellaHeader 0
#define COCOAPODS_VERSION_MINOR_libextobjc_UmbrellaHeader 4
#define COCOAPODS_VERSION_PATCH_libextobjc_UmbrellaHeader 0

