// This file is automatically generated at build time from your asset catalogs.
// Any edits you make will be overwritten.

#import <Foundation/Foundation.h>

@interface LSImagesCatalog: NSObject

+(UIImage *)placeholder_cell;
+(UIImage *)orange_navbar;
+(UIImage *)ic_m_traffic;
+(UIImage *)Image;
+(UIImage *)ic_m_webcam;
+(UIImage *)glyphicons_054_clock;
+(UIImage *)green_navbar;
+(UIImage *)waza_be;
+(UIImage *)bg_speedlimit;
+(UIImage *)blue_navbar;
+(UIImage *)red_navbar;
+(UIImage *)Icon;
+(UIImage *)Default;
+(UIImage *)qkaiser;
+(UIImage *)ic_m_radar;
+(UIImage *)Traffic;
+(UIImage *)menu;
+(UIImage *)navbar;
+(UIImage *)harkor;
+(UIImage *)Cameras;
+(UIImage *)bg_list;
+(UIImage *)Map;
+(UIImage *)Radars;
+(UIImage *)About;
+(UIImage *)Settings;
+(UIImage *)valcapri;
+(UIImage *)glyphicons_309_comments;

@end