// This file is automatically generated at build time from your storyboards.
// Any edits you make will be overwritten.

#import "StoryboardIdentifiers.h"

#pragma mark Main

const struct LSMainStoryboardIDs LSMainStoryboardIDs = {
    .segues = {
        .detailTrafficEvent = @"detailTrafficEvent",
    },

    .viewControllers = {
        .map = @"MapViewController",
        .about = @"AboutViewController",
        .camerasNavigation = @"CamerasNavigationController",
        .cameras = @"CamerasViewController",
        .settings = @"SettingsViewController",
        .mapNavigation = @"MapNavigationController",
        .menu = @"MenuViewController",
        .initialSliding = @"InitialSlidingViewController",
        .trafficEventDetailNavigation = @"TrafficEventDetailNavigationController",
        .trafficDetail = @"TrafficDetailViewController",
        .radars = @"RadarsViewController",
        .radarsNavigation = @"RadarsNavigationController",
        .settingsNavigation = @"SettingsNavigationController",
        .trafficNavigation = @"TrafficNavigationController",
        .trafficEvents = @"TrafficEventsViewController",
        .aboutNavigation = @"AboutNavigationController",
        .split = @"SplitViewController",
    },

    .reusables = {
        .detailTrafficEvent = @"detailTrafficEvent",
        .menuItemCell = @"MenuItemCell",
        .beroadsCell = @"beroadsCell",
        .beRoadsRadarCell = @"beRoadsRadarCell",
        .contactCell = @"contactCell",
    },

};