// This file is automatically generated at build time from your storyboards.
// Any edits you make will be overwritten.

#import <Foundation/Foundation.h>

#pragma mark Main

extern const struct LSMainStoryboardIDs {
    struct {
        __unsafe_unretained NSString *detailTrafficEvent;
        __unsafe_unretained NSString *detailCamera;
    } segues;

    struct {
        __unsafe_unretained NSString *map;
        __unsafe_unretained NSString *about;
        __unsafe_unretained NSString *camerasNavigation;
        __unsafe_unretained NSString *cameras;
        __unsafe_unretained NSString *cameraDetail;
        __unsafe_unretained NSString *settings;
        __unsafe_unretained NSString *mapNavigation;
        __unsafe_unretained NSString *menu;
        __unsafe_unretained NSString *initialSliding;
        __unsafe_unretained NSString *trafficDetail;
        __unsafe_unretained NSString *radars;
        __unsafe_unretained NSString *radarsNavigation;
        __unsafe_unretained NSString *settingsNavigation;
        __unsafe_unretained NSString *trafficNavigation;
        __unsafe_unretained NSString *trafficEvents;
        __unsafe_unretained NSString *aboutNavigation;
        __unsafe_unretained NSString *split;
    } viewControllers;

    struct {
        __unsafe_unretained NSString *detailTrafficEvent;
        __unsafe_unretained NSString *menuItemCell;
        __unsafe_unretained NSString *beroadsCell;
        __unsafe_unretained NSString *beRoadsRadarCell;
        __unsafe_unretained NSString *contactCell;
    } reusables;

} LSMainStoryboardIDs;